### ISSUE TITLE
docker-compose not working

### ISSUE THREAD

**Issue by FreezyExp** [Fuglesteg/timid#1]
```
version: '3.4'

services:
    valheim:
        volumes:
            - './config:/config'
            - './data:/opt/valheim'
        environment:
            - SERVER_PASS='Example'
            - SERVER_PUBLIC=true
            - TZ='Europe/Amsterdam'
            - VALHEIM_PLUS=true
            - VALHEIM_PLUS_REPO='Grantapher/ValheimPlus'
        image: lloesche/valheim-server
        cap_add:
            - sys_nice
        restart: "no"
        stop_grace_period: 2m
        labels:
            - timid.group.valheim
    timid:
        image: fuglesteg/timid
        restart: always
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
          - "2456-2458:2456-2458/udp"
        environment:
          TIMID_PORT: 2456
          TIMID_TARGET_ADDRESS: valheim:2456
          TIMID_CONTAINER_GROUP: valheim
          TIMID_GROUP_NAME: valheim
```

This fails with
Error: read udp 172.0.0.2:37642->172.0.0.3:2456: read: connection refused

Then after the container is stopped:
```
Starting containers
Error: Error response from daemon: No such container: <hash>
Error: Error: No such container: <hash>

```
The docker-compose definition from the readme also does not work, as the "name" is not a valid top level definition.

Can anyone help me?
